# Generated by Django 6.0.5 on 2026-05-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagement.product')),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non Fiction'), ('biography', 'Biography'), ('science', 'Science'), ('history', 'History'), ('other', 'Other')], default='other', max_length=50)),
                ('published_year', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
            bases=('inventoryManagement.product',),
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagement.product')),
                ('expiry_date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('is_perishable', models.BooleanField(default=True)),
                ('storage_temp', models.CharField(choices=[('ambient', 'Ambient (Room Temp)'), ('chilled', 'Chilled (2-8°C)'), ('frozen', 'Frozen (-18°C)')], default='ambient', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Food Product',
                'verbose_name_plural': 'Food Products',
            },
            bases=('inventoryManagement.product',),
        ),
        migrations.CreateModel(
            name='StationeryProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagement.product')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('pen', 'Pen'), ('pencil', 'Pencil'), ('notebook', 'Notebook'), ('ruler', 'Ruler'), ('eraser', 'Eraser'), ('other', 'Other')], default='other', max_length=50)),
            ],
            options={
                'verbose_name': 'Stationery Product',
                'verbose_name_plural': 'Stationery Products',
            },
            bases=('inventoryManagement.product',),
        ),
        migrations.CreateModel(
            name='TextbookProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagement.product')),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12')], default='grade_1', max_length=20)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('published_year', models.IntegerField(blank=True, null=True)),
                ('curriculum', models.CharField(choices=[('caps', 'CAPS'), ('ieb', 'IEB'), ('other', 'Other')], default='caps', max_length=50)),
            ],
            options={
                'verbose_name': 'Textbook',
                'verbose_name_plural': 'Textbooks',
            },
            bases=('inventoryManagement.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
