# Generated by Django 6.0.5 on 2026-05-19 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventoryManagement', '0002_bookproduct_foodproduct_stationeryproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/stock/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('reserved', 'Reserved'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='new', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'ordering': ['product', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='bookproduct',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('biography', 'Biography'), ('science', 'Science'), ('history', 'History'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='storage_temp',
            field=models.CharField(choices=[('ambient', 'Ambient (Room Temp)'), ('chilled', 'Chilled (2–8°C)'), ('frozen', 'Frozen (−18°C)')], default='ambient', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/products/'),
        ),
        migrations.CreateModel(
            name='BookStockItem',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagement.stockitem')),
                ('copy_number', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Book Stock Item',
                'verbose_name_plural': 'Book Stock Items',
            },
            bases=('inventoryManagement.stockitem',),
        ),
        migrations.CreateModel(
            name='FoodStockItem',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagement.stockitem')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Food Stock Item',
                'verbose_name_plural': 'Food Stock Items',
            },
            bases=('inventoryManagement.stockitem',),
        ),
        migrations.CreateModel(
            name='OtherStockItem',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagement.stockitem')),
                ('item_type', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Other Stock Item',
                'verbose_name_plural': 'Other Stock Items',
            },
            bases=('inventoryManagement.stockitem',),
        ),
        migrations.CreateModel(
            name='StationeryStockItem',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagement.stockitem')),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Stationery Stock Item',
                'verbose_name_plural': 'Stationery Stock Items',
            },
            bases=('inventoryManagement.stockitem',),
        ),
        migrations.CreateModel(
            name='TextbookStockItem',
            fields=[
                ('stockitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventoryManagement.stockitem')),
                ('copy_number', models.IntegerField(default=1)),
                ('issued_to', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('return_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Textbook Stock Item',
                'verbose_name_plural': 'Textbook Stock Items',
            },
            bases=('inventoryManagement.stockitem',),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventoryManagement.product'),
        ),
    ]
