# Generated by Django 6.0.5 on 2026-05-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0003_stockitem_alter_bookproduct_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
