# Generated by Django 6.0.5 on 2026-05-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0004_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['id'], 'verbose_name': 'Stock Item', 'verbose_name_plural': 'Stock Items'},
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='product',
        ),
        migrations.AddField(
            model_name='bookstockitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventoryManagement.bookproduct'),
        ),
        migrations.AddField(
            model_name='foodstockitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventoryManagement.foodproduct'),
        ),
        migrations.AddField(
            model_name='stationerystockitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventoryManagement.stationeryproduct'),
        ),
        migrations.AddField(
            model_name='textbookstockitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventoryManagement.textbookproduct'),
        ),
        migrations.DeleteModel(
            name='OtherStockItem',
        ),
    ]
