# Generated by Django 6.0.5 on 2026-05-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0006_alter_foodproduct_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/books/'),
        ),
        migrations.AddField(
            model_name='textbookproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/textbooks/'),
        ),
    ]
