# Generated by Django 6.0.5 on 2026-06-19 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0007_bookproduct_image_textbookproduct_image'),
        ('library', '0002_remove_bookborrowed_book_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorymanagementProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventoryManagement_product',
            },
        ),
        migrations.CreateModel(
            name='InventorymanagementStockitem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'inventoryManagement_stockitem',
            },
        ),
        migrations.RemoveField(
            model_name='bookstockitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bookstockitem',
            name='stockitem_ptr',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='foodstockitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='foodstockitem',
            name='stockitem_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='stationeryproduct',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='textbookproduct',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='stationerystockitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stationerystockitem',
            name='stockitem_ptr',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='textbookstockitem',
            name='stockitem_ptr',
        ),
        migrations.RemoveField(
            model_name='textbookstockitem',
            name='product',
        ),
        migrations.CreateModel(
            name='InventorymanagementBookproduct',
            fields=[
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryManagement.inventorymanagementproduct')),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('published_year', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inventoryManagement_bookproduct',
            },
        ),
        migrations.CreateModel(
            name='InventorymanagementFoodproduct',
            fields=[
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryManagement.inventorymanagementproduct')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('is_perishable', models.BooleanField()),
                ('storage_temp', models.CharField(max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'inventoryManagement_foodproduct',
            },
        ),
        migrations.CreateModel(
            name='InventorymanagementStationeryproduct',
            fields=[
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryManagement.inventorymanagementproduct')),
                ('brand', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inventoryManagement_stationeryproduct',
            },
        ),
        migrations.CreateModel(
            name='InventorymanagementTextbookproduct',
            fields=[
                ('product_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryManagement.inventorymanagementproduct')),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('edition', models.CharField(max_length=50)),
                ('published_year', models.IntegerField(blank=True, null=True)),
                ('curriculum', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inventoryManagement_textbookproduct',
            },
        ),
        migrations.CreateModel(
            name='InventorymanagementBookstockitem',
            fields=[
                ('stockitem_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryManagement.inventorymanagementstockitem')),
                ('copy_number', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryManagement.inventorymanagementbookproduct')),
            ],
            options={
                'db_table': 'inventoryManagement_bookstockitem',
            },
        ),
        migrations.CreateModel(
            name='InventorymanagementFoodstockitem',
            fields=[
                ('stockitem_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryManagement.inventorymanagementstockitem')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(max_length=50)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryManagement.inventorymanagementfoodproduct')),
            ],
            options={
                'db_table': 'inventoryManagement_foodstockitem',
            },
        ),
        migrations.CreateModel(
            name='InventorymanagementStationerystockitem',
            fields=[
                ('stockitem_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryManagement.inventorymanagementstockitem')),
                ('colour', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryManagement.inventorymanagementstationeryproduct')),
            ],
            options={
                'db_table': 'inventoryManagement_stationerystockitem',
            },
        ),
        migrations.CreateModel(
            name='InventorymanagementTextbookstockitem',
            fields=[
                ('stockitem_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventoryManagement.inventorymanagementstockitem')),
                ('copy_number', models.IntegerField()),
                ('issued_to', models.CharField(max_length=200)),
                ('is_available', models.BooleanField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryManagement.inventorymanagementtextbookproduct')),
            ],
            options={
                'db_table': 'inventoryManagement_textbookstockitem',
            },
        ),
        migrations.DeleteModel(
            name='BookProduct',
        ),
        migrations.DeleteModel(
            name='BookStockItem',
        ),
        migrations.DeleteModel(
            name='FoodProduct',
        ),
        migrations.DeleteModel(
            name='FoodStockItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='StationeryProduct',
        ),
        migrations.DeleteModel(
            name='StationeryStockItem',
        ),
        migrations.DeleteModel(
            name='StockItem',
        ),
        migrations.DeleteModel(
            name='TextbookProduct',
        ),
        migrations.DeleteModel(
            name='TextbookStockItem',
        ),
    ]
