# Generated by Django 6.0.5 on 2026-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0008_inventorymanagementproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymanagementproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorymanagementproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventorymanagementproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inventorymanagementproduct',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='inventorymanagementproduct',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='inventorymanagementproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorymanagementproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorymanagementproduct',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorymanagementproduct',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorymanagementproduct',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorymanagementproduct',
            name='qrcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorymanagementproduct',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventorymanagementproduct',
            name='received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorymanagementproduct',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymanagementproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorymanagementproduct',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
