# Generated by Django 6.0.5 on 2026-06-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0009_remove_inventorymanagementproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventorymanagementproduct',
            table='inventorymanagement_product',
        ),
    ]
