# Generated by Django 6.0.7 on 2026-07-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryManagement', '0010_alter_inventorymanagementproduct_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventorymanagementbookproduct',
            table='book',
        ),
    ]
