--
-- PostgreSQL database dump
--

\restrict MnpMesZAj9O0sWweXJhtRxiyOrb5J43Ssuv0f23gIeddS2rqaPrGTBvjBr3HaOf

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-07-03 16:43:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 24591)
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    id integer NOT NULL,
    user_id integer
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24590)
-- Name: admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.admin_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.admin_id_seq OWNER TO postgres;

--
-- TOC entry 5507 (class 0 OID 0)
-- Dependencies: 221
-- Name: admin_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.admin_id_seq OWNED BY public.admin.id;


--
-- TOC entry 273 (class 1259 OID 24993)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 272 (class 1259 OID 24992)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 275 (class 1259 OID 25003)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 274 (class 1259 OID 25002)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 24983)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 24982)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 283 (class 1259 OID 25079)
-- Name: authentication_cookprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_cookprofile (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authentication_cookprofile OWNER TO postgres;

--
-- TOC entry 282 (class 1259 OID 25078)
-- Name: authentication_cookprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_cookprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_cookprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 285 (class 1259 OID 25090)
-- Name: authentication_learnerprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_learnerprofile (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authentication_learnerprofile OWNER TO postgres;

--
-- TOC entry 284 (class 1259 OID 25089)
-- Name: authentication_learnerprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_learnerprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_learnerprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 287 (class 1259 OID 25102)
-- Name: authentication_librarianprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_librarianprofile (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authentication_librarianprofile OWNER TO postgres;

--
-- TOC entry 286 (class 1259 OID 25101)
-- Name: authentication_librarianprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_librarianprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_librarianprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 289 (class 1259 OID 25113)
-- Name: authentication_teacherprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_teacherprofile (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authentication_teacherprofile OWNER TO postgres;

--
-- TOC entry 288 (class 1259 OID 25112)
-- Name: authentication_teacherprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_teacherprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_teacherprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 277 (class 1259 OID 25040)
-- Name: authentication_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL
);


ALTER TABLE public.authentication_user OWNER TO postgres;

--
-- TOC entry 279 (class 1259 OID 25061)
-- Name: authentication_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.authentication_user_groups OWNER TO postgres;

--
-- TOC entry 278 (class 1259 OID 25060)
-- Name: authentication_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 25039)
-- Name: authentication_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 281 (class 1259 OID 25070)
-- Name: authentication_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.authentication_user_user_permissions OWNER TO postgres;

--
-- TOC entry 280 (class 1259 OID 25069)
-- Name: authentication_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 24912)
-- Name: bill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bill (
    id integer NOT NULL,
    learner_id integer,
    amount numeric(10,2),
    bill_date date,
    status character varying(50)
);


ALTER TABLE public.bill OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 24911)
-- Name: bill_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bill_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.bill_id_seq OWNER TO postgres;

--
-- TOC entry 5508 (class 0 OID 0)
-- Dependencies: 260
-- Name: bill_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.bill_id_seq OWNED BY public.bill.id;


--
-- TOC entry 232 (class 1259 OID 24668)
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    id integer NOT NULL,
    title character varying(255),
    author character varying(255),
    category character varying(100),
    isbn character varying(30)
);


ALTER TABLE public.book OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 24691)
-- Name: book_borrowed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book_borrowed (
    id integer NOT NULL,
    learner_id integer,
    librarian_id integer,
    borrow_date date,
    due_date date,
    return_date date
);


ALTER TABLE public.book_borrowed OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 24690)
-- Name: book_borrowed_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.book_borrowed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.book_borrowed_id_seq OWNER TO postgres;

--
-- TOC entry 5509 (class 0 OID 0)
-- Dependencies: 235
-- Name: book_borrowed_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.book_borrowed_id_seq OWNED BY public.book_borrowed.id;


--
-- TOC entry 231 (class 1259 OID 24667)
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.book_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.book_id_seq OWNER TO postgres;

--
-- TOC entry 5510 (class 0 OID 0)
-- Dependencies: 231
-- Name: book_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.book_id_seq OWNED BY public.book.id;


--
-- TOC entry 234 (class 1259 OID 24678)
-- Name: book_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book_item (
    id integer NOT NULL,
    book_id integer,
    barcode character varying(100),
    status character varying(50)
);


ALTER TABLE public.book_item OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 24677)
-- Name: book_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.book_item_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.book_item_id_seq OWNER TO postgres;

--
-- TOC entry 5511 (class 0 OID 0)
-- Dependencies: 233
-- Name: book_item_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.book_item_id_seq OWNED BY public.book_item.id;


--
-- TOC entry 310 (class 1259 OID 25666)
-- Name: book_queue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book_queue (
    id integer NOT NULL,
    book_isbn character varying(20) NOT NULL,
    student_username character varying(150) NOT NULL,
    added_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) DEFAULT 'waiting'::character varying
);


ALTER TABLE public.book_queue OWNER TO postgres;

--
-- TOC entry 309 (class 1259 OID 25665)
-- Name: book_queue_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.book_queue_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.book_queue_id_seq OWNER TO postgres;

--
-- TOC entry 5512 (class 0 OID 0)
-- Dependencies: 309
-- Name: book_queue_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.book_queue_id_seq OWNED BY public.book_queue.id;


--
-- TOC entry 308 (class 1259 OID 25624)
-- Name: borrowed_books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.borrowed_books (
    id integer NOT NULL,
    learner_username character varying(150) NOT NULL,
    asset_id integer NOT NULL,
    borrowed_date date DEFAULT CURRENT_DATE,
    loan_period interval NOT NULL,
    due_date date NOT NULL,
    librarian_username character varying(150) NOT NULL,
    status character varying(20) DEFAULT 'Active'::character varying
);


ALTER TABLE public.borrowed_books OWNER TO postgres;

--
-- TOC entry 307 (class 1259 OID 25623)
-- Name: borrowed_books_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.borrowed_books_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.borrowed_books_id_seq OWNER TO postgres;

--
-- TOC entry 5513 (class 0 OID 0)
-- Dependencies: 307
-- Name: borrowed_books_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.borrowed_books_id_seq OWNED BY public.borrowed_books.id;


--
-- TOC entry 230 (class 1259 OID 24653)
-- Name: cook; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cook (
    id integer NOT NULL,
    user_id integer
);


ALTER TABLE public.cook OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 24652)
-- Name: cook_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cook_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cook_id_seq OWNER TO postgres;

--
-- TOC entry 5514 (class 0 OID 0)
-- Dependencies: 229
-- Name: cook_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cook_id_seq OWNED BY public.cook.id;


--
-- TOC entry 263 (class 1259 OID 24925)
-- Name: delivery_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delivery_log (
    id integer NOT NULL,
    admin_id integer,
    delivery_date date,
    delivery_type character varying(100),
    description text
);


ALTER TABLE public.delivery_log OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 24924)
-- Name: delivery_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.delivery_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.delivery_log_id_seq OWNER TO postgres;

--
-- TOC entry 5515 (class 0 OID 0)
-- Dependencies: 262
-- Name: delivery_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.delivery_log_id_seq OWNED BY public.delivery_log.id;


--
-- TOC entry 291 (class 1259 OID 25174)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 290 (class 1259 OID 25173)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 24971)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 24970)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 24959)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 24958)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 304 (class 1259 OID 25455)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 24726)
-- Name: food; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food (
    id integer NOT NULL,
    food_name character varying(100),
    category character varying(100)
);


ALTER TABLE public.food OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 24760)
-- Name: food_cooked; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_cooked (
    id integer NOT NULL,
    cook_id integer,
    cooked_date date,
    quantity integer
);


ALTER TABLE public.food_cooked OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 24759)
-- Name: food_cooked_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.food_cooked_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.food_cooked_id_seq OWNER TO postgres;

--
-- TOC entry 5516 (class 0 OID 0)
-- Dependencies: 243
-- Name: food_cooked_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.food_cooked_id_seq OWNED BY public.food_cooked.id;


--
-- TOC entry 246 (class 1259 OID 24773)
-- Name: food_distributed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_distributed (
    id integer NOT NULL,
    learner_id integer,
    cook_id integer,
    queue_id integer,
    distributed_date date
);


ALTER TABLE public.food_distributed OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 24772)
-- Name: food_distributed_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.food_distributed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.food_distributed_id_seq OWNER TO postgres;

--
-- TOC entry 5517 (class 0 OID 0)
-- Dependencies: 245
-- Name: food_distributed_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.food_distributed_id_seq OWNED BY public.food_distributed.id;


--
-- TOC entry 247 (class 1259 OID 24795)
-- Name: food_distribution_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_distribution_items (
    food_distributed_id integer NOT NULL,
    food_item_id integer NOT NULL
);


ALTER TABLE public.food_distribution_items OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 24725)
-- Name: food_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.food_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.food_id_seq OWNER TO postgres;

--
-- TOC entry 5518 (class 0 OID 0)
-- Dependencies: 237
-- Name: food_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.food_id_seq OWNED BY public.food.id;


--
-- TOC entry 240 (class 1259 OID 24734)
-- Name: food_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.food_item (
    id integer NOT NULL,
    food_id integer,
    quantity integer,
    unit character varying(50)
);


ALTER TABLE public.food_item OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 24733)
-- Name: food_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.food_item_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.food_item_id_seq OWNER TO postgres;

--
-- TOC entry 5519 (class 0 OID 0)
-- Dependencies: 239
-- Name: food_item_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.food_item_id_seq OWNED BY public.food_item.id;


--
-- TOC entry 294 (class 1259 OID 25214)
-- Name: inventoryManagement_bookproduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_bookproduct" (
    product_ptr_id integer NOT NULL,
    author character varying(200) NOT NULL,
    isbn character varying(20) NOT NULL,
    publisher character varying(200) NOT NULL,
    genre character varying(50) NOT NULL,
    published_year integer,
    language character varying(50) NOT NULL,
    pages integer,
    image character varying(100)
);


ALTER TABLE public."inventoryManagement_bookproduct" OWNER TO postgres;

--
-- TOC entry 300 (class 1259 OID 25303)
-- Name: inventoryManagement_bookstockitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_bookstockitem" (
    stockitem_ptr_id bigint NOT NULL,
    copy_number integer NOT NULL,
    is_available boolean NOT NULL,
    product_id integer
);


ALTER TABLE public."inventoryManagement_bookstockitem" OWNER TO postgres;

--
-- TOC entry 295 (class 1259 OID 25227)
-- Name: inventoryManagement_foodproduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_foodproduct" (
    product_ptr_id integer NOT NULL,
    expiry_date date,
    supplier character varying(100) NOT NULL,
    is_perishable boolean NOT NULL,
    storage_temp character varying(20) NOT NULL,
    weight_kg numeric(6,3)
);


ALTER TABLE public."inventoryManagement_foodproduct" OWNER TO postgres;

--
-- TOC entry 301 (class 1259 OID 25311)
-- Name: inventoryManagement_foodstockitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_foodstockitem" (
    stockitem_ptr_id bigint NOT NULL,
    expiry_date date,
    batch_number character varying(50) NOT NULL,
    weight_kg numeric(6,3),
    product_id integer
);


ALTER TABLE public."inventoryManagement_foodstockitem" OWNER TO postgres;

--
-- TOC entry 293 (class 1259 OID 25201)
-- Name: inventoryManagement_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_product" (
    id integer NOT NULL,
    name character varying(255),
    polymorphic_ctype_id integer,
    brand character varying(100),
    category character varying(100),
    condition character varying(100),
    image text,
    location character varying(100),
    qrcode text,
    qty integer,
    received date,
    supplier character varying(255)
);


ALTER TABLE public."inventoryManagement_product" OWNER TO postgres;

--
-- TOC entry 292 (class 1259 OID 25200)
-- Name: inventoryManagement_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."inventoryManagement_product" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."inventoryManagement_product_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 296 (class 1259 OID 25237)
-- Name: inventoryManagement_stationeryproduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_stationeryproduct" (
    product_ptr_id integer NOT NULL,
    brand character varying(100) NOT NULL,
    colour character varying(50) NOT NULL,
    category character varying(50) NOT NULL
);


ALTER TABLE public."inventoryManagement_stationeryproduct" OWNER TO postgres;

--
-- TOC entry 302 (class 1259 OID 25327)
-- Name: inventoryManagement_stationerystockitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_stationerystockitem" (
    stockitem_ptr_id bigint CONSTRAINT "inventoryManagement_stationerystockit_stockitem_ptr_id_not_null" NOT NULL,
    colour character varying(50) NOT NULL,
    quantity integer NOT NULL,
    product_id integer
);


ALTER TABLE public."inventoryManagement_stationerystockitem" OWNER TO postgres;

--
-- TOC entry 299 (class 1259 OID 25290)
-- Name: inventoryManagement_stockitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_stockitem" (
    id bigint NOT NULL,
    qr_code character varying(100),
    status character varying(20) NOT NULL,
    condition character varying(20) NOT NULL,
    added_at timestamp with time zone,
    updated_at timestamp with time zone,
    notes text NOT NULL,
    polymorphic_ctype_id integer
);


ALTER TABLE public."inventoryManagement_stockitem" OWNER TO postgres;

--
-- TOC entry 298 (class 1259 OID 25289)
-- Name: inventoryManagement_stockitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."inventoryManagement_stockitem" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."inventoryManagement_stockitem_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 297 (class 1259 OID 25246)
-- Name: inventoryManagement_textbookproduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_textbookproduct" (
    product_ptr_id integer NOT NULL,
    author character varying(200) NOT NULL,
    isbn character varying(20) NOT NULL,
    publisher character varying(200) NOT NULL,
    subject character varying(100) NOT NULL,
    grade character varying(20) NOT NULL,
    edition character varying(50) NOT NULL,
    published_year integer,
    curriculum character varying(50) NOT NULL,
    image character varying(100)
);


ALTER TABLE public."inventoryManagement_textbookproduct" OWNER TO postgres;

--
-- TOC entry 303 (class 1259 OID 25335)
-- Name: inventoryManagement_textbookstockitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."inventoryManagement_textbookstockitem" (
    stockitem_ptr_id bigint NOT NULL,
    copy_number integer NOT NULL,
    issued_to character varying(200) NOT NULL,
    is_available boolean NOT NULL,
    return_date date,
    product_id integer
);


ALTER TABLE public."inventoryManagement_textbookstockitem" OWNER TO postgres;

--
-- TOC entry 306 (class 1259 OID 25486)
-- Name: inventorymanagement_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventorymanagement_product (
    id integer NOT NULL,
    name character varying(255),
    brand character varying(100),
    category character varying(100),
    qty integer DEFAULT 0,
    received date,
    supplier character varying(255),
    condition character varying(100),
    location character varying(100),
    image text,
    qrcode text
);


ALTER TABLE public.inventorymanagement_product OWNER TO postgres;

--
-- TOC entry 305 (class 1259 OID 25485)
-- Name: inventorymanagement_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.inventorymanagement_product_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.inventorymanagement_product_id_seq OWNER TO postgres;

--
-- TOC entry 5520 (class 0 OID 0)
-- Dependencies: 305
-- Name: inventorymanagement_product_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.inventorymanagement_product_id_seq OWNED BY public.inventorymanagement_product.id;


--
-- TOC entry 226 (class 1259 OID 24623)
-- Name: learner; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.learner (
    id integer NOT NULL,
    user_id integer,
    grade character varying(20),
    classroom character varying(20)
);


ALTER TABLE public.learner OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24622)
-- Name: learner_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.learner_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.learner_id_seq OWNER TO postgres;

--
-- TOC entry 5521 (class 0 OID 0)
-- Dependencies: 225
-- Name: learner_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.learner_id_seq OWNED BY public.learner.id;


--
-- TOC entry 228 (class 1259 OID 24638)
-- Name: librarian; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.librarian (
    id integer NOT NULL,
    user_id integer
);


ALTER TABLE public.librarian OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24637)
-- Name: librarian_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.librarian_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.librarian_id_seq OWNER TO postgres;

--
-- TOC entry 5522 (class 0 OID 0)
-- Dependencies: 227
-- Name: librarian_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.librarian_id_seq OWNED BY public.librarian.id;


--
-- TOC entry 242 (class 1259 OID 24747)
-- Name: queue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.queue (
    id integer NOT NULL,
    queue_number integer,
    learner_id integer
);


ALTER TABLE public.queue OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 24746)
-- Name: queue_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.queue_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.queue_id_seq OWNER TO postgres;

--
-- TOC entry 5523 (class 0 OID 0)
-- Dependencies: 241
-- Name: queue_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.queue_id_seq OWNED BY public.queue.id;


--
-- TOC entry 249 (class 1259 OID 24813)
-- Name: stationery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stationery (
    id integer NOT NULL,
    name character varying(255),
    quantity integer,
    unit character varying(50)
);


ALTER TABLE public.stationery OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 24821)
-- Name: stationery_distribution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stationery_distribution (
    id integer NOT NULL,
    learner_id integer,
    teacher_id integer,
    distribution_date date
);


ALTER TABLE public.stationery_distribution OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 24820)
-- Name: stationery_distribution_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.stationery_distribution_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.stationery_distribution_id_seq OWNER TO postgres;

--
-- TOC entry 5524 (class 0 OID 0)
-- Dependencies: 250
-- Name: stationery_distribution_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.stationery_distribution_id_seq OWNED BY public.stationery_distribution.id;


--
-- TOC entry 252 (class 1259 OID 24838)
-- Name: stationery_distribution_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stationery_distribution_items (
    distribution_id integer NOT NULL,
    stationery_id integer NOT NULL,
    quantity integer
);


ALTER TABLE public.stationery_distribution_items OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 24812)
-- Name: stationery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.stationery_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.stationery_id_seq OWNER TO postgres;

--
-- TOC entry 5525 (class 0 OID 0)
-- Dependencies: 248
-- Name: stationery_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.stationery_id_seq OWNED BY public.stationery.id;


--
-- TOC entry 224 (class 1259 OID 24606)
-- Name: teacher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher (
    id integer NOT NULL,
    user_id integer,
    qualification character varying(255),
    subject_speciality character varying(255)
);


ALTER TABLE public.teacher OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24605)
-- Name: teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.teacher_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.teacher_id_seq OWNER TO postgres;

--
-- TOC entry 5526 (class 0 OID 0)
-- Dependencies: 223
-- Name: teacher_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.teacher_id_seq OWNED BY public.teacher.id;


--
-- TOC entry 254 (class 1259 OID 24856)
-- Name: textbook; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.textbook (
    id integer NOT NULL,
    title character varying(255),
    subject character varying(100),
    grade character varying(20),
    isbn character varying(30)
);


ALTER TABLE public.textbook OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 24877)
-- Name: textbook_allocation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.textbook_allocation (
    id integer NOT NULL,
    learner_id integer,
    teacher_id integer,
    allocation_date date
);


ALTER TABLE public.textbook_allocation OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 24876)
-- Name: textbook_allocation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.textbook_allocation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.textbook_allocation_id_seq OWNER TO postgres;

--
-- TOC entry 5527 (class 0 OID 0)
-- Dependencies: 257
-- Name: textbook_allocation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.textbook_allocation_id_seq OWNED BY public.textbook_allocation.id;


--
-- TOC entry 259 (class 1259 OID 24894)
-- Name: textbook_allocation_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.textbook_allocation_items (
    allocation_id integer NOT NULL,
    textbook_item_id integer NOT NULL
);


ALTER TABLE public.textbook_allocation_items OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 24855)
-- Name: textbook_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.textbook_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.textbook_id_seq OWNER TO postgres;

--
-- TOC entry 5528 (class 0 OID 0)
-- Dependencies: 253
-- Name: textbook_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.textbook_id_seq OWNED BY public.textbook.id;


--
-- TOC entry 256 (class 1259 OID 24864)
-- Name: textbook_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.textbook_item (
    id integer NOT NULL,
    textbook_id integer,
    barcode character varying(100),
    status character varying(50)
);


ALTER TABLE public.textbook_item OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 24863)
-- Name: textbook_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.textbook_item_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.textbook_item_id_seq OWNER TO postgres;

--
-- TOC entry 5529 (class 0 OID 0)
-- Dependencies: 255
-- Name: textbook_item_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.textbook_item_id_seq OWNED BY public.textbook_item.id;


--
-- TOC entry 265 (class 1259 OID 24940)
-- Name: user_register; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_register (
    id integer NOT NULL,
    user_id integer,
    registered_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.user_register OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 24939)
-- Name: user_register_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_register_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_register_id_seq OWNER TO postgres;

--
-- TOC entry 5530 (class 0 OID 0)
-- Dependencies: 264
-- Name: user_register_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_register_id_seq OWNED BY public.user_register.id;


--
-- TOC entry 220 (class 1259 OID 24578)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    email character varying(255),
    password character varying(255),
    role character varying(50),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    username character varying(150),
    last_login timestamp with time zone,
    date_joined timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    is_superuser boolean DEFAULT false,
    is_staff boolean DEFAULT false,
    is_active boolean DEFAULT true
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24577)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 5531 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 5105 (class 2604 OID 24594)
-- Name: admin id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin ALTER COLUMN id SET DEFAULT nextval('public.admin_id_seq'::regclass);


--
-- TOC entry 5123 (class 2604 OID 24915)
-- Name: bill id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bill ALTER COLUMN id SET DEFAULT nextval('public.bill_id_seq'::regclass);


--
-- TOC entry 5110 (class 2604 OID 24671)
-- Name: book id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book ALTER COLUMN id SET DEFAULT nextval('public.book_id_seq'::regclass);


--
-- TOC entry 5112 (class 2604 OID 24694)
-- Name: book_borrowed id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_borrowed ALTER COLUMN id SET DEFAULT nextval('public.book_borrowed_id_seq'::regclass);


--
-- TOC entry 5111 (class 2604 OID 24681)
-- Name: book_item id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_item ALTER COLUMN id SET DEFAULT nextval('public.book_item_id_seq'::regclass);


--
-- TOC entry 5132 (class 2604 OID 25669)
-- Name: book_queue id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_queue ALTER COLUMN id SET DEFAULT nextval('public.book_queue_id_seq'::regclass);


--
-- TOC entry 5129 (class 2604 OID 25627)
-- Name: borrowed_books id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowed_books ALTER COLUMN id SET DEFAULT nextval('public.borrowed_books_id_seq'::regclass);


--
-- TOC entry 5109 (class 2604 OID 24656)
-- Name: cook id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cook ALTER COLUMN id SET DEFAULT nextval('public.cook_id_seq'::regclass);


--
-- TOC entry 5124 (class 2604 OID 24928)
-- Name: delivery_log id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_log ALTER COLUMN id SET DEFAULT nextval('public.delivery_log_id_seq'::regclass);


--
-- TOC entry 5113 (class 2604 OID 24729)
-- Name: food id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food ALTER COLUMN id SET DEFAULT nextval('public.food_id_seq'::regclass);


--
-- TOC entry 5116 (class 2604 OID 24763)
-- Name: food_cooked id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_cooked ALTER COLUMN id SET DEFAULT nextval('public.food_cooked_id_seq'::regclass);


--
-- TOC entry 5117 (class 2604 OID 24776)
-- Name: food_distributed id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_distributed ALTER COLUMN id SET DEFAULT nextval('public.food_distributed_id_seq'::regclass);


--
-- TOC entry 5114 (class 2604 OID 24737)
-- Name: food_item id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_item ALTER COLUMN id SET DEFAULT nextval('public.food_item_id_seq'::regclass);


--
-- TOC entry 5127 (class 2604 OID 25489)
-- Name: inventorymanagement_product id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventorymanagement_product ALTER COLUMN id SET DEFAULT nextval('public.inventorymanagement_product_id_seq'::regclass);


--
-- TOC entry 5107 (class 2604 OID 24626)
-- Name: learner id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learner ALTER COLUMN id SET DEFAULT nextval('public.learner_id_seq'::regclass);


--
-- TOC entry 5108 (class 2604 OID 24641)
-- Name: librarian id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.librarian ALTER COLUMN id SET DEFAULT nextval('public.librarian_id_seq'::regclass);


--
-- TOC entry 5115 (class 2604 OID 24750)
-- Name: queue id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.queue ALTER COLUMN id SET DEFAULT nextval('public.queue_id_seq'::regclass);


--
-- TOC entry 5118 (class 2604 OID 24816)
-- Name: stationery id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stationery ALTER COLUMN id SET DEFAULT nextval('public.stationery_id_seq'::regclass);


--
-- TOC entry 5119 (class 2604 OID 24824)
-- Name: stationery_distribution id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stationery_distribution ALTER COLUMN id SET DEFAULT nextval('public.stationery_distribution_id_seq'::regclass);


--
-- TOC entry 5106 (class 2604 OID 24609)
-- Name: teacher id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher ALTER COLUMN id SET DEFAULT nextval('public.teacher_id_seq'::regclass);


--
-- TOC entry 5120 (class 2604 OID 24859)
-- Name: textbook id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook ALTER COLUMN id SET DEFAULT nextval('public.textbook_id_seq'::regclass);


--
-- TOC entry 5122 (class 2604 OID 24880)
-- Name: textbook_allocation id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_allocation ALTER COLUMN id SET DEFAULT nextval('public.textbook_allocation_id_seq'::regclass);


--
-- TOC entry 5121 (class 2604 OID 24867)
-- Name: textbook_item id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_item ALTER COLUMN id SET DEFAULT nextval('public.textbook_item_id_seq'::regclass);


--
-- TOC entry 5125 (class 2604 OID 24943)
-- Name: user_register id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_register ALTER COLUMN id SET DEFAULT nextval('public.user_register_id_seq'::regclass);


--
-- TOC entry 5099 (class 2604 OID 24581)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 5142 (class 2606 OID 24597)
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (id);


--
-- TOC entry 5144 (class 2606 OID 24599)
-- Name: admin admin_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_user_id_key UNIQUE (user_id);


--
-- TOC entry 5217 (class 2606 OID 25036)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 5222 (class 2606 OID 25021)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 5225 (class 2606 OID 25010)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5219 (class 2606 OID 24999)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 5212 (class 2606 OID 25012)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 5214 (class 2606 OID 24991)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5244 (class 2606 OID 25086)
-- Name: authentication_cookprofile authentication_cookprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_cookprofile
    ADD CONSTRAINT authentication_cookprofile_pkey PRIMARY KEY (id);


--
-- TOC entry 5246 (class 2606 OID 25088)
-- Name: authentication_cookprofile authentication_cookprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_cookprofile
    ADD CONSTRAINT authentication_cookprofile_user_id_key UNIQUE (user_id);


--
-- TOC entry 5248 (class 2606 OID 25098)
-- Name: authentication_learnerprofile authentication_learnerprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_learnerprofile
    ADD CONSTRAINT authentication_learnerprofile_pkey PRIMARY KEY (id);


--
-- TOC entry 5250 (class 2606 OID 25100)
-- Name: authentication_learnerprofile authentication_learnerprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_learnerprofile
    ADD CONSTRAINT authentication_learnerprofile_user_id_key UNIQUE (user_id);


--
-- TOC entry 5252 (class 2606 OID 25109)
-- Name: authentication_librarianprofile authentication_librarianprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_librarianprofile
    ADD CONSTRAINT authentication_librarianprofile_pkey PRIMARY KEY (id);


--
-- TOC entry 5254 (class 2606 OID 25111)
-- Name: authentication_librarianprofile authentication_librarianprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_librarianprofile
    ADD CONSTRAINT authentication_librarianprofile_user_id_key UNIQUE (user_id);


--
-- TOC entry 5256 (class 2606 OID 25121)
-- Name: authentication_teacherprofile authentication_teacherprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_teacherprofile
    ADD CONSTRAINT authentication_teacherprofile_pkey PRIMARY KEY (id);


--
-- TOC entry 5258 (class 2606 OID 25123)
-- Name: authentication_teacherprofile authentication_teacherprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_teacherprofile
    ADD CONSTRAINT authentication_teacherprofile_user_id_key UNIQUE (user_id);


--
-- TOC entry 5233 (class 2606 OID 25068)
-- Name: authentication_user_groups authentication_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 5236 (class 2606 OID 25126)
-- Name: authentication_user_groups authentication_user_groups_user_id_group_id_8af031ac_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user_groups_user_id_group_id_8af031ac_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 5227 (class 2606 OID 25057)
-- Name: authentication_user authentication_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user
    ADD CONSTRAINT authentication_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5239 (class 2606 OID 25077)
-- Name: authentication_user_user_permissions authentication_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5242 (class 2606 OID 25140)
-- Name: authentication_user_user_permissions authentication_user_user_user_id_permission_id_ec51b09f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user_user_user_id_permission_id_ec51b09f_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 5230 (class 2606 OID 25059)
-- Name: authentication_user authentication_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user
    ADD CONSTRAINT authentication_user_username_key UNIQUE (username);


--
-- TOC entry 5199 (class 2606 OID 24918)
-- Name: bill bill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bill
    ADD CONSTRAINT bill_pkey PRIMARY KEY (id);


--
-- TOC entry 5170 (class 2606 OID 24697)
-- Name: book_borrowed book_borrowed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_borrowed
    ADD CONSTRAINT book_borrowed_pkey PRIMARY KEY (id);


--
-- TOC entry 5168 (class 2606 OID 24684)
-- Name: book_item book_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_item
    ADD CONSTRAINT book_item_pkey PRIMARY KEY (id);


--
-- TOC entry 5163 (class 2606 OID 24676)
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id);


--
-- TOC entry 5298 (class 2606 OID 25676)
-- Name: book_queue book_queue_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_queue
    ADD CONSTRAINT book_queue_pkey PRIMARY KEY (id);


--
-- TOC entry 5296 (class 2606 OID 25637)
-- Name: borrowed_books borrowed_books_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowed_books
    ADD CONSTRAINT borrowed_books_pkey PRIMARY KEY (id);


--
-- TOC entry 5159 (class 2606 OID 24659)
-- Name: cook cook_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cook
    ADD CONSTRAINT cook_pkey PRIMARY KEY (id);


--
-- TOC entry 5161 (class 2606 OID 24661)
-- Name: cook cook_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cook
    ADD CONSTRAINT cook_user_id_key UNIQUE (user_id);


--
-- TOC entry 5201 (class 2606 OID 24933)
-- Name: delivery_log delivery_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_log
    ADD CONSTRAINT delivery_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5261 (class 2606 OID 25187)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5207 (class 2606 OID 24981)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 5209 (class 2606 OID 24979)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 5205 (class 2606 OID 24969)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5291 (class 2606 OID 25464)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5179 (class 2606 OID 24766)
-- Name: food_cooked food_cooked_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_cooked
    ADD CONSTRAINT food_cooked_pkey PRIMARY KEY (id);


--
-- TOC entry 5181 (class 2606 OID 24779)
-- Name: food_distributed food_distributed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_distributed
    ADD CONSTRAINT food_distributed_pkey PRIMARY KEY (id);


--
-- TOC entry 5183 (class 2606 OID 24801)
-- Name: food_distribution_items food_distribution_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_distribution_items
    ADD CONSTRAINT food_distribution_items_pkey PRIMARY KEY (food_distributed_id, food_item_id);


--
-- TOC entry 5175 (class 2606 OID 24740)
-- Name: food_item food_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_item
    ADD CONSTRAINT food_item_pkey PRIMARY KEY (id);


--
-- TOC entry 5172 (class 2606 OID 24732)
-- Name: food food_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food
    ADD CONSTRAINT food_pkey PRIMARY KEY (id);


--
-- TOC entry 5267 (class 2606 OID 25510)
-- Name: inventoryManagement_bookproduct inventoryManagement_bookproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_bookproduct"
    ADD CONSTRAINT "inventoryManagement_bookproduct_pkey" PRIMARY KEY (product_ptr_id);


--
-- TOC entry 5278 (class 2606 OID 25310)
-- Name: inventoryManagement_bookstockitem inventoryManagement_bookstockitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_bookstockitem"
    ADD CONSTRAINT "inventoryManagement_bookstockitem_pkey" PRIMARY KEY (stockitem_ptr_id);


--
-- TOC entry 5269 (class 2606 OID 25525)
-- Name: inventoryManagement_foodproduct inventoryManagement_foodproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_foodproduct"
    ADD CONSTRAINT "inventoryManagement_foodproduct_pkey" PRIMARY KEY (product_ptr_id);


--
-- TOC entry 5281 (class 2606 OID 25317)
-- Name: inventoryManagement_foodstockitem inventoryManagement_foodstockitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_foodstockitem"
    ADD CONSTRAINT "inventoryManagement_foodstockitem_pkey" PRIMARY KEY (stockitem_ptr_id);


--
-- TOC entry 5264 (class 2606 OID 25499)
-- Name: inventoryManagement_product inventoryManagement_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_product"
    ADD CONSTRAINT "inventoryManagement_product_pkey" PRIMARY KEY (id);


--
-- TOC entry 5271 (class 2606 OID 25538)
-- Name: inventoryManagement_stationeryproduct inventoryManagement_stationeryproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_stationeryproduct"
    ADD CONSTRAINT "inventoryManagement_stationeryproduct_pkey" PRIMARY KEY (product_ptr_id);


--
-- TOC entry 5284 (class 2606 OID 25334)
-- Name: inventoryManagement_stationerystockitem inventoryManagement_stationerystockitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_stationerystockitem"
    ADD CONSTRAINT "inventoryManagement_stationerystockitem_pkey" PRIMARY KEY (stockitem_ptr_id);


--
-- TOC entry 5275 (class 2606 OID 25302)
-- Name: inventoryManagement_stockitem inventoryManagement_stockitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_stockitem"
    ADD CONSTRAINT "inventoryManagement_stockitem_pkey" PRIMARY KEY (id);


--
-- TOC entry 5273 (class 2606 OID 25551)
-- Name: inventoryManagement_textbookproduct inventoryManagement_textbookproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_textbookproduct"
    ADD CONSTRAINT "inventoryManagement_textbookproduct_pkey" PRIMARY KEY (product_ptr_id);


--
-- TOC entry 5287 (class 2606 OID 25343)
-- Name: inventoryManagement_textbookstockitem inventoryManagement_textbookstockitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_textbookstockitem"
    ADD CONSTRAINT "inventoryManagement_textbookstockitem_pkey" PRIMARY KEY (stockitem_ptr_id);


--
-- TOC entry 5294 (class 2606 OID 25495)
-- Name: inventorymanagement_product inventorymanagement_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventorymanagement_product
    ADD CONSTRAINT inventorymanagement_product_pkey PRIMARY KEY (id);


--
-- TOC entry 5151 (class 2606 OID 24629)
-- Name: learner learner_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learner
    ADD CONSTRAINT learner_pkey PRIMARY KEY (id);


--
-- TOC entry 5153 (class 2606 OID 24631)
-- Name: learner learner_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learner
    ADD CONSTRAINT learner_user_id_key UNIQUE (user_id);


--
-- TOC entry 5155 (class 2606 OID 24644)
-- Name: librarian librarian_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.librarian
    ADD CONSTRAINT librarian_pkey PRIMARY KEY (id);


--
-- TOC entry 5157 (class 2606 OID 24646)
-- Name: librarian librarian_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.librarian
    ADD CONSTRAINT librarian_user_id_key UNIQUE (user_id);


--
-- TOC entry 5177 (class 2606 OID 24753)
-- Name: queue queue_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.queue
    ADD CONSTRAINT queue_pkey PRIMARY KEY (id);


--
-- TOC entry 5189 (class 2606 OID 24844)
-- Name: stationery_distribution_items stationery_distribution_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stationery_distribution_items
    ADD CONSTRAINT stationery_distribution_items_pkey PRIMARY KEY (distribution_id, stationery_id);


--
-- TOC entry 5187 (class 2606 OID 24827)
-- Name: stationery_distribution stationery_distribution_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stationery_distribution
    ADD CONSTRAINT stationery_distribution_pkey PRIMARY KEY (id);


--
-- TOC entry 5185 (class 2606 OID 24819)
-- Name: stationery stationery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stationery
    ADD CONSTRAINT stationery_pkey PRIMARY KEY (id);


--
-- TOC entry 5146 (class 2606 OID 24614)
-- Name: teacher teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (id);


--
-- TOC entry 5148 (class 2606 OID 24616)
-- Name: teacher teacher_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_user_id_key UNIQUE (user_id);


--
-- TOC entry 5197 (class 2606 OID 24900)
-- Name: textbook_allocation_items textbook_allocation_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_allocation_items
    ADD CONSTRAINT textbook_allocation_items_pkey PRIMARY KEY (allocation_id, textbook_item_id);


--
-- TOC entry 5195 (class 2606 OID 24883)
-- Name: textbook_allocation textbook_allocation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_allocation
    ADD CONSTRAINT textbook_allocation_pkey PRIMARY KEY (id);


--
-- TOC entry 5193 (class 2606 OID 24870)
-- Name: textbook_item textbook_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_item
    ADD CONSTRAINT textbook_item_pkey PRIMARY KEY (id);


--
-- TOC entry 5191 (class 2606 OID 24862)
-- Name: textbook textbook_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook
    ADD CONSTRAINT textbook_pkey PRIMARY KEY (id);


--
-- TOC entry 5166 (class 2606 OID 25664)
-- Name: book unique_book_isbn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT unique_book_isbn UNIQUE (isbn);


--
-- TOC entry 5203 (class 2606 OID 24947)
-- Name: user_register user_register_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_register
    ADD CONSTRAINT user_register_pkey PRIMARY KEY (id);


--
-- TOC entry 5138 (class 2606 OID 24589)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 5140 (class 2606 OID 24587)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 5215 (class 1259 OID 25037)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 5220 (class 1259 OID 25032)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 5223 (class 1259 OID 25033)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 5210 (class 1259 OID 25018)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 5231 (class 1259 OID 25138)
-- Name: authentication_user_groups_group_id_6b5c44b7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_user_groups_group_id_6b5c44b7 ON public.authentication_user_groups USING btree (group_id);


--
-- TOC entry 5234 (class 1259 OID 25137)
-- Name: authentication_user_groups_user_id_30868577; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_user_groups_user_id_30868577 ON public.authentication_user_groups USING btree (user_id);


--
-- TOC entry 5237 (class 1259 OID 25152)
-- Name: authentication_user_user_permissions_permission_id_ea6be19a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_user_user_permissions_permission_id_ea6be19a ON public.authentication_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5240 (class 1259 OID 25151)
-- Name: authentication_user_user_permissions_user_id_736ebf7e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_user_user_permissions_user_id_736ebf7e ON public.authentication_user_user_permissions USING btree (user_id);


--
-- TOC entry 5228 (class 1259 OID 25124)
-- Name: authentication_user_username_a09a089e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_user_username_a09a089e_like ON public.authentication_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 5259 (class 1259 OID 25198)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5262 (class 1259 OID 25199)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5289 (class 1259 OID 25466)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5292 (class 1259 OID 25465)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5164 (class 1259 OID 24954)
-- Name: idx_book_title; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_book_title ON public.book USING btree (title);


--
-- TOC entry 5173 (class 1259 OID 24955)
-- Name: idx_food_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_food_name ON public.food USING btree (food_name);


--
-- TOC entry 5149 (class 1259 OID 24956)
-- Name: idx_learner_grade; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_learner_grade ON public.learner USING btree (grade);


--
-- TOC entry 5136 (class 1259 OID 24953)
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- TOC entry 5279 (class 1259 OID 25518)
-- Name: inventoryManagement_bookstockitem_product_id_dbe930e5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "inventoryManagement_bookstockitem_product_id_dbe930e5" ON public."inventoryManagement_bookstockitem" USING btree (product_id);


--
-- TOC entry 5282 (class 1259 OID 25531)
-- Name: inventoryManagement_foodstockitem_product_id_780b8675; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "inventoryManagement_foodstockitem_product_id_780b8675" ON public."inventoryManagement_foodstockitem" USING btree (product_id);


--
-- TOC entry 5265 (class 1259 OID 25288)
-- Name: inventoryManagement_product_polymorphic_ctype_id_7efbebe2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "inventoryManagement_product_polymorphic_ctype_id_7efbebe2" ON public."inventoryManagement_product" USING btree (polymorphic_ctype_id);


--
-- TOC entry 5285 (class 1259 OID 25544)
-- Name: inventoryManagement_stationerystockitem_product_id_031070cd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "inventoryManagement_stationerystockitem_product_id_031070cd" ON public."inventoryManagement_stationerystockitem" USING btree (product_id);


--
-- TOC entry 5276 (class 1259 OID 25355)
-- Name: inventoryManagement_stockitem_polymorphic_ctype_id_69c101f2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "inventoryManagement_stockitem_polymorphic_ctype_id_69c101f2" ON public."inventoryManagement_stockitem" USING btree (polymorphic_ctype_id);


--
-- TOC entry 5288 (class 1259 OID 25559)
-- Name: inventoryManagement_textbookstockitem_product_id_0e00dd48; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "inventoryManagement_textbookstockitem_product_id_0e00dd48" ON public."inventoryManagement_textbookstockitem" USING btree (product_id);


--
-- TOC entry 5299 (class 2606 OID 24600)
-- Name: admin admin_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 5328 (class 2606 OID 25027)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5329 (class 2606 OID 25022)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5327 (class 2606 OID 25013)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5334 (class 2606 OID 25153)
-- Name: authentication_cookprofile authentication_cookp_user_id_f3815d07_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_cookprofile
    ADD CONSTRAINT authentication_cookp_user_id_f3815d07_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5335 (class 2606 OID 25158)
-- Name: authentication_learnerprofile authentication_learn_user_id_e4a393cb_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_learnerprofile
    ADD CONSTRAINT authentication_learn_user_id_e4a393cb_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5336 (class 2606 OID 25163)
-- Name: authentication_librarianprofile authentication_libra_user_id_77f5dff2_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_librarianprofile
    ADD CONSTRAINT authentication_libra_user_id_77f5dff2_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5337 (class 2606 OID 25168)
-- Name: authentication_teacherprofile authentication_teach_user_id_9f84cb45_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_teacherprofile
    ADD CONSTRAINT authentication_teach_user_id_9f84cb45_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5332 (class 2606 OID 25146)
-- Name: authentication_user_user_permissions authentication_user__permission_id_ea6be19a_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user__permission_id_ea6be19a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5330 (class 2606 OID 25127)
-- Name: authentication_user_groups authentication_user__user_id_30868577_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user__user_id_30868577_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5333 (class 2606 OID 25141)
-- Name: authentication_user_user_permissions authentication_user__user_id_736ebf7e_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user__user_id_736ebf7e_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5331 (class 2606 OID 25132)
-- Name: authentication_user_groups authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5324 (class 2606 OID 24919)
-- Name: bill bill_learner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bill
    ADD CONSTRAINT bill_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.learner(id);


--
-- TOC entry 5305 (class 2606 OID 24698)
-- Name: book_borrowed book_borrowed_learner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_borrowed
    ADD CONSTRAINT book_borrowed_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.learner(id);


--
-- TOC entry 5306 (class 2606 OID 24703)
-- Name: book_borrowed book_borrowed_librarian_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_borrowed
    ADD CONSTRAINT book_borrowed_librarian_id_fkey FOREIGN KEY (librarian_id) REFERENCES public.librarian(id);


--
-- TOC entry 5304 (class 2606 OID 24685)
-- Name: book_item book_item_book_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_item
    ADD CONSTRAINT book_item_book_id_fkey FOREIGN KEY (book_id) REFERENCES public.book(id);


--
-- TOC entry 5303 (class 2606 OID 24662)
-- Name: cook cook_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cook
    ADD CONSTRAINT cook_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 5325 (class 2606 OID 24934)
-- Name: delivery_log delivery_log_admin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_log
    ADD CONSTRAINT delivery_log_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin(id);


--
-- TOC entry 5338 (class 2606 OID 25188)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5339 (class 2606 OID 25193)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5354 (class 2606 OID 25677)
-- Name: book_queue fk_queue_book; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book_queue
    ADD CONSTRAINT fk_queue_book FOREIGN KEY (book_isbn) REFERENCES public.book(isbn) ON DELETE CASCADE;


--
-- TOC entry 5309 (class 2606 OID 24767)
-- Name: food_cooked food_cooked_cook_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_cooked
    ADD CONSTRAINT food_cooked_cook_id_fkey FOREIGN KEY (cook_id) REFERENCES public.cook(id);


--
-- TOC entry 5310 (class 2606 OID 24785)
-- Name: food_distributed food_distributed_cook_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_distributed
    ADD CONSTRAINT food_distributed_cook_id_fkey FOREIGN KEY (cook_id) REFERENCES public.cook(id);


--
-- TOC entry 5311 (class 2606 OID 24780)
-- Name: food_distributed food_distributed_learner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_distributed
    ADD CONSTRAINT food_distributed_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.learner(id);


--
-- TOC entry 5312 (class 2606 OID 24790)
-- Name: food_distributed food_distributed_queue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_distributed
    ADD CONSTRAINT food_distributed_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES public.queue(id);


--
-- TOC entry 5313 (class 2606 OID 24802)
-- Name: food_distribution_items food_distribution_items_food_distributed_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_distribution_items
    ADD CONSTRAINT food_distribution_items_food_distributed_id_fkey FOREIGN KEY (food_distributed_id) REFERENCES public.food_distributed(id);


--
-- TOC entry 5314 (class 2606 OID 24807)
-- Name: food_distribution_items food_distribution_items_food_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_distribution_items
    ADD CONSTRAINT food_distribution_items_food_item_id_fkey FOREIGN KEY (food_item_id) REFERENCES public.food_item(id);


--
-- TOC entry 5307 (class 2606 OID 24741)
-- Name: food_item food_item_food_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.food_item
    ADD CONSTRAINT food_item_food_id_fkey FOREIGN KEY (food_id) REFERENCES public.food(id);


--
-- TOC entry 5345 (class 2606 OID 25350)
-- Name: inventoryManagement_stockitem inventoryManagement__polymorphic_ctype_id_69c101f2_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_stockitem"
    ADD CONSTRAINT "inventoryManagement__polymorphic_ctype_id_69c101f2_fk_django_co" FOREIGN KEY (polymorphic_ctype_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5340 (class 2606 OID 25261)
-- Name: inventoryManagement_product inventoryManagement__polymorphic_ctype_id_7efbebe2_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_product"
    ADD CONSTRAINT "inventoryManagement__polymorphic_ctype_id_7efbebe2_fk_django_co" FOREIGN KEY (polymorphic_ctype_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5346 (class 2606 OID 25356)
-- Name: inventoryManagement_bookstockitem inventoryManagement__stockitem_ptr_id_2470bdd3_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_bookstockitem"
    ADD CONSTRAINT "inventoryManagement__stockitem_ptr_id_2470bdd3_fk_inventory" FOREIGN KEY (stockitem_ptr_id) REFERENCES public."inventoryManagement_stockitem"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5350 (class 2606 OID 25371)
-- Name: inventoryManagement_stationerystockitem inventoryManagement__stockitem_ptr_id_28e6ae5c_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_stationerystockitem"
    ADD CONSTRAINT "inventoryManagement__stockitem_ptr_id_28e6ae5c_fk_inventory" FOREIGN KEY (stockitem_ptr_id) REFERENCES public."inventoryManagement_stockitem"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5348 (class 2606 OID 25361)
-- Name: inventoryManagement_foodstockitem inventoryManagement__stockitem_ptr_id_624f745d_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_foodstockitem"
    ADD CONSTRAINT "inventoryManagement__stockitem_ptr_id_624f745d_fk_inventory" FOREIGN KEY (stockitem_ptr_id) REFERENCES public."inventoryManagement_stockitem"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5352 (class 2606 OID 25376)
-- Name: inventoryManagement_textbookstockitem inventoryManagement__stockitem_ptr_id_7067b1cd_fk_inventory; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_textbookstockitem"
    ADD CONSTRAINT "inventoryManagement__stockitem_ptr_id_7067b1cd_fk_inventory" FOREIGN KEY (stockitem_ptr_id) REFERENCES public."inventoryManagement_stockitem"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5341 (class 2606 OID 25565)
-- Name: inventoryManagement_bookproduct inventoryManagement_bookproduct_product_ptr_id_ea22550d_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_bookproduct"
    ADD CONSTRAINT "inventoryManagement_bookproduct_product_ptr_id_ea22550d_fk" FOREIGN KEY (product_ptr_id) REFERENCES public."inventoryManagement_product"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5347 (class 2606 OID 25570)
-- Name: inventoryManagement_bookstockitem inventoryManagement_bookstockitem_product_id_dbe930e5_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_bookstockitem"
    ADD CONSTRAINT "inventoryManagement_bookstockitem_product_id_dbe930e5_fk" FOREIGN KEY (product_id) REFERENCES public."inventoryManagement_bookproduct"(product_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5342 (class 2606 OID 25575)
-- Name: inventoryManagement_foodproduct inventoryManagement_foodproduct_product_ptr_id_d01d129f_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_foodproduct"
    ADD CONSTRAINT "inventoryManagement_foodproduct_product_ptr_id_d01d129f_fk" FOREIGN KEY (product_ptr_id) REFERENCES public."inventoryManagement_product"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5349 (class 2606 OID 25580)
-- Name: inventoryManagement_foodstockitem inventoryManagement_foodstockitem_product_id_780b8675_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_foodstockitem"
    ADD CONSTRAINT "inventoryManagement_foodstockitem_product_id_780b8675_fk" FOREIGN KEY (product_id) REFERENCES public."inventoryManagement_foodproduct"(product_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5343 (class 2606 OID 25585)
-- Name: inventoryManagement_stationeryproduct inventoryManagement_stati_product_ptr_id_1f2e6706_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_stationeryproduct"
    ADD CONSTRAINT "inventoryManagement_stati_product_ptr_id_1f2e6706_fk" FOREIGN KEY (product_ptr_id) REFERENCES public."inventoryManagement_product"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5351 (class 2606 OID 25590)
-- Name: inventoryManagement_stationerystockitem inventoryManagement_stationerystockitem_product_id_031070cd_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_stationerystockitem"
    ADD CONSTRAINT "inventoryManagement_stationerystockitem_product_id_031070cd_fk" FOREIGN KEY (product_id) REFERENCES public."inventoryManagement_stationeryproduct"(product_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5344 (class 2606 OID 25595)
-- Name: inventoryManagement_textbookproduct inventoryManagement_textbookproduct_product_ptr_id_4372c7d4_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_textbookproduct"
    ADD CONSTRAINT "inventoryManagement_textbookproduct_product_ptr_id_4372c7d4_fk" FOREIGN KEY (product_ptr_id) REFERENCES public."inventoryManagement_product"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5353 (class 2606 OID 25600)
-- Name: inventoryManagement_textbookstockitem inventoryManagement_textbookstockitem_product_id_0e00dd48_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."inventoryManagement_textbookstockitem"
    ADD CONSTRAINT "inventoryManagement_textbookstockitem_product_id_0e00dd48_fk" FOREIGN KEY (product_id) REFERENCES public."inventoryManagement_textbookproduct"(product_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5301 (class 2606 OID 24632)
-- Name: learner learner_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learner
    ADD CONSTRAINT learner_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 5302 (class 2606 OID 24647)
-- Name: librarian librarian_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.librarian
    ADD CONSTRAINT librarian_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 5308 (class 2606 OID 24754)
-- Name: queue queue_learner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.queue
    ADD CONSTRAINT queue_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.learner(id);


--
-- TOC entry 5317 (class 2606 OID 24845)
-- Name: stationery_distribution_items stationery_distribution_items_distribution_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stationery_distribution_items
    ADD CONSTRAINT stationery_distribution_items_distribution_id_fkey FOREIGN KEY (distribution_id) REFERENCES public.stationery_distribution(id);


--
-- TOC entry 5318 (class 2606 OID 24850)
-- Name: stationery_distribution_items stationery_distribution_items_stationery_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stationery_distribution_items
    ADD CONSTRAINT stationery_distribution_items_stationery_id_fkey FOREIGN KEY (stationery_id) REFERENCES public.stationery(id);


--
-- TOC entry 5315 (class 2606 OID 24828)
-- Name: stationery_distribution stationery_distribution_learner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stationery_distribution
    ADD CONSTRAINT stationery_distribution_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.learner(id);


--
-- TOC entry 5316 (class 2606 OID 24833)
-- Name: stationery_distribution stationery_distribution_teacher_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stationery_distribution
    ADD CONSTRAINT stationery_distribution_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher(id);


--
-- TOC entry 5300 (class 2606 OID 24617)
-- Name: teacher teacher_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 5322 (class 2606 OID 24901)
-- Name: textbook_allocation_items textbook_allocation_items_allocation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_allocation_items
    ADD CONSTRAINT textbook_allocation_items_allocation_id_fkey FOREIGN KEY (allocation_id) REFERENCES public.textbook_allocation(id);


--
-- TOC entry 5323 (class 2606 OID 24906)
-- Name: textbook_allocation_items textbook_allocation_items_textbook_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_allocation_items
    ADD CONSTRAINT textbook_allocation_items_textbook_item_id_fkey FOREIGN KEY (textbook_item_id) REFERENCES public.textbook_item(id);


--
-- TOC entry 5320 (class 2606 OID 24884)
-- Name: textbook_allocation textbook_allocation_learner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_allocation
    ADD CONSTRAINT textbook_allocation_learner_id_fkey FOREIGN KEY (learner_id) REFERENCES public.learner(id);


--
-- TOC entry 5321 (class 2606 OID 24889)
-- Name: textbook_allocation textbook_allocation_teacher_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_allocation
    ADD CONSTRAINT textbook_allocation_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teacher(id);


--
-- TOC entry 5319 (class 2606 OID 24871)
-- Name: textbook_item textbook_item_textbook_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.textbook_item
    ADD CONSTRAINT textbook_item_textbook_id_fkey FOREIGN KEY (textbook_id) REFERENCES public.textbook(id);


--
-- TOC entry 5326 (class 2606 OID 24948)
-- Name: user_register user_register_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_register
    ADD CONSTRAINT user_register_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2026-07-03 16:43:45

--
-- PostgreSQL database dump complete
--

\unrestrict MnpMesZAj9O0sWweXJhtRxiyOrb5J43Ssuv0f23gIeddS2rqaPrGTBvjBr3HaOf

