# Generated by Django 6.0.5 on 2026-05-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_cookproxy_learnerproxy_librarianproxy_teacherproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookprofile',
            name='kitchen_station',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='learnerprofile',
            name='student_number',
        ),
        migrations.RemoveField(
            model_name='librarianprofile',
            name='library_section',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subject',
        ),
    ]
