# Generated by Django 6.0.5 on 2026-06-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_cookprofile_kitchen_station_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CookProxy',
        ),
        migrations.DeleteModel(
            name='LearnerProxy',
        ),
        migrations.DeleteModel(
            name='LibrarianProxy',
        ),
        migrations.DeleteModel(
            name='TeacherProxy',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='cookprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='librarianprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='cookprofile',
            table='authentication_cookprofile',
        ),
        migrations.AlterModelTable(
            name='learnerprofile',
            table='authentication_learnerprofile',
        ),
        migrations.AlterModelTable(
            name='librarianprofile',
            table='authentication_librarianprofile',
        ),
        migrations.AlterModelTable(
            name='teacherprofile',
            table='authentication_teacherprofile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='authentication_user',
        ),
    ]
