"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cj#np+a^_@brjfqf@io1s^9he^2@*z!)wgm7iw%&nm-smwd_ol'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'authentication',
    'inventoryManagement',
    'polymorphic',
    'library',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'inventory_db',
        'USER': 'postgres',
        'PASSWORD': 'kamo2012',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# custom user model
AUTH_USER_MODEL = 'authentication.User'

# Media files (for QR code images)
import os
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5502",
    "http://localhost:5502",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    "http://127.0.0.1:5000",
    "http://localhost:5000",
]

# For development: allow all origins (change this in production)
CORS_ALLOW_ALL_ORIGINS = True
JAZZMIN_SETTINGS = {
    # ── Branding ──────────────────────────────────────────────────────
    "site_title":        "IMS Admin",
    "site_header":       "Inventory Management System",
    "site_brand":        "IMS",
    "site_logo":         None,
    "welcome_sign":      "Welcome to IMS Admin",
    "copyright":         "IMS 2026",

    # ── Top links ─────────────────────────────────────────────────────
    "topmenu_links": [
        {"name": "Home",      "url": "admin:index"},
        {"name": "Site",      "url": "/",           "new_window": True},
        {"app": "users"},
        {"app": "inventoryManagement"},
        {"app": "library"},
    ],

    # ── User menu ─────────────────────────────────────────────────────
    "usermenu_links": [
        {"name": "Support",   "url": "#", "new_window": True},
        {"model": "auth.user"},
    ],

    # ── Sidebar ───────────────────────────────────────────────────────
    "show_sidebar":          True,
    "navigation_expanded":   True,
    "hide_apps":             [],
    "hide_models":           [],

    # ── Order sidebar sections ────────────────────────────────────────
    "order_with_respect_to": [
        "users",
        "inventoryManagement",
        "library",
        "auth",
    ],

    # ── Custom sidebar links ──────────────────────────────────────────
    "custom_links": {
        "inventoryManagement": [
            {
                "name":        "All Stock Items",
                "url":         "admin:inventoryManagement_stockitem_changelist",
                "icon":        "fas fa-boxes",
                "permissions": ["is_staff"],
            }
        ],
        "library": [
            {
                "name":        "Borrowed Books",
                "url":         "admin:library_bookborrowed_changelist",
                "icon":        "fas fa-book-open",
                "permissions": ["is_staff"],
            }
        ],
    },

    # ── Icons ─────────────────────────────────────────────────────────
    "icons": {
        # Users app
        "users.User":           "fas fa-user",
        "users.TeacherProxy":   "fas fa-chalkboard-teacher",
        "users.LearnerProxy":   "fas fa-user-graduate",
        "users.CookProxy":      "fas fa-utensils",
        "users.LibrarianProxy": "fas fa-book-reader",

        # Inventory app
        "inventoryManagement.Product":            "fas fa-box",
        "inventoryManagement.StationeryProduct":  "fas fa-pen",
        "inventoryManagement.FoodProduct":        "fas fa-apple-alt",
        "inventoryManagement.BookProduct":        "fas fa-book",
        "inventoryManagement.TextbookProduct":    "fas fa-graduation-cap",
        "inventoryManagement.StockItem":          "fas fa-boxes",
        "inventoryManagement.StationeryStockItem":"fas fa-pen-nib",
        "inventoryManagement.FoodStockItem":      "fas fa-drumstick-bite",
        "inventoryManagement.BookStockItem":      "fas fa-bookmark",
        "inventoryManagement.TextbookStockItem":  "fas fa-book-open",
        "inventoryManagement.OtherStockItem":     "fas fa-question-circle",

        # Library app
        "library.BookBorrowed": "fas fa-hand-holding-heart",
        "library.Bill":         "fas fa-file-invoice-dollar",

        # Auth
        "auth.Group": "fas fa-users",
    },

    "default_icon_parents":  "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # ── UI tweaks ──────────────────────────────────────────────────────
    "related_modal_active":   True,
    "custom_css":             None,
    "custom_js":              None,
    "use_google_fonts_cdn":   True,
    "show_ui_builder":        False,    # set True to customise live
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text":        False,
    "footer_small_text":        False,
    "body_small_text":          False,
    "brand_small_text":         False,
    "brand_colour":             "navbar-dark",
    "accent":                   "accent-primary",
    "navbar":                   "navbar-dark",
    "no_navbar_border":         False,
    "navbar_fixed":             True,
    "layout_boxed":             False,
    "footer_fixed":             False,
    "sidebar_fixed":            True,
    "sidebar":                  "sidebar-dark-primary",
    "sidebar_nav_small_text":   False,
    "sidebar_disable_expand":   False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style":False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style":   False,
    "theme":                    "default",
    "dark_mode_theme":          None,
    "button_classes": {
        "primary":   "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}